config/routes.rb
Rails.application.routes.draw do
    
  get 'images/show'

    resources :brands do
       resources :models 
    end
    
    resources :characteristic_types
    
    resources :phones do
        resources :characteristic_values
    end
    
    resources :images
    
    resources :orders
    
    root 'phones#index'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :model
  validates :name, :price, presence: true
  has_many :characteristic_values, dependent: :destroy
  has_many :orders
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
    
    before_action :authenticate, :except => [:index, :show]
    
    def index
       
        @pageTitle = "Список телефонов"
        @phones = Phone.all.model.all
        @order = Order.new
    end
    
    def show
        
        @phone = Phone.find(params[:id])
        @pageTitle = @phone.name
        @charValues = @phone.characteristic_values.all
        @order = Order.new
    end
    
    def new
       
       @pageTitle = "Добавить телефон"
       @phone = Phone.new
       
       @brands = Brand.all
       @models = Model.all
    end
    
    def edit
        
        @phone = Phone.find(params[:id])
        @pageTitle = @phone.name
    end
    
    def create
        
        @image = Image.new(image_params)
        
        if @image.save
            
            @phone = Phone.new(phone_params)
            
            @phone.image_id = @image.id
            
            if @phone.save
                redirect_to @phone
            else
                @pageTitle = "Добавить телефон"
                render new_phone_path
            end      
        else
            @pageTitle = "Добавить телефон"
            render new_phone_path
        end
    end
    
    def update
       
        @phone = Phone.find(params[:id])
        
        if !image_params.blank?
            
            @phone.image.filename = params[:phone][:file].original_filename
            @phone.image.content_type = params[:phone][:file].content_type
            @phone.image.file_contents = params[:phone][:file].read
            
            @phone.image.update_attributes(image_params)
        end
        
        if @phone.update(phone_params)
            @pageTitle = @phone.name
            redirect_to @phone
        else 
            render edit_phone_path(@phone)
        end
    end
    
    def destroy
        
        @phone = Phone.find(params[:id])
        if !@phone.image_id.nil?
            @image = Image.find(@phone.image_id)
            if !@image.nil?
                @phone.image_id = nil
                @phone.image_id = nil
                @phone.update_attributes({:image_id => nil})
                @image.destroy
            end
        end
        @phone.destroy
     
        redirect_to phones_path
    end
    
    private
    
        def phone_params
           params.require(:phone).permit(:id, :name, :description, :model_id, :price, :sort, :rating, :date_realese, :image_id)
        end
        
        def image_params
            params.require(:phone).permit(:file)
        end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.erb
  <div class="form-wrapper">
    <%= form_with model: @phone, local: true do |form| %>
      
      <script>
        var brandsStr = '<%= @brands.to_json.html_safe %>'.trim();
        var brands = JSON.parse(brandsStr);
        var modelStr = '<%= @models.to_json.html_safe %>'.trim();
        var models = JSON.parse(modelStr);
      </script>
    
      <% if @phone.errors.any? %>
        <div class="form-errors">
            Производитель не был добавлен. Были обнаружены следующие ошибки:
          <ul>
            <% @phone.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= form.label :name, "Имя" %>
        <%= form.text_field :name , { :class => "form-control", :required => true} %>
      </div>
     
      <div class="form-group">
       <%= form.label :description, "Описание" %>
       <%= form.text_area :description, { :class => "form-control"} %>
      </div>
      
      <div class="form-group">
       <%= form.label :price,  "Цена" %>
       <%= form.number_field :price, { :class => "form-control", :required => true} %>
      </div>
      
      <div class="form-group">
        <%= form.label :model_id, "Бренд" %>
        <%= form.collection_select( :brand_id,Brand.all, :id, :name, {}, { :class => "form-control"}) %>
      </div>
      
      <div class="form-group">
        <%= form.label :model_id, "Модель" %>
        <%= form.collection_select(:model_id, Model.all, :id, :name, {}, { :class => "form-control"}) %>
      </div>
      
      <div class="form-group">
       <%= form.label :rating, { :value => "Рейтинг"} %>
       <%= form.select :rating, [
          ['1',1],
          ['2',2],
          ['3',3],
          ['4',4],
          ['5',5],
       ], {}, { :class => "form-control"} %>
      </div>
      
      <div class="form-group">
       <%= form.label :sort,  "Сортировка" %>
       <%= form.number_field :sort, { :class => "form-control"} %>
      </div>
      
      <div class="form-group">
       <%= form.label :realese_date, "Дата выхода" %>
       <%= form.date_field :realese_date, { :class => "form-control"} %>
      </div>
      
      <div class="form-group">
        <%= form.label :file, "Изображение" %>
        <%= form.file_field :file, { :class => "form-control"} %>
      </div>
      
      <%= form.submit "Отправить", { :class => "btn btn-primary" } %>
      
    <% end %>
  </div>

app/views/phones/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

<div class="container">
  <div class="bottom-page-links">
    <%= link_to "Телефоны", phones_path, { :class => "btn btn-primary btn-block" } %>
  </div>
</div>

app/views/phones/index.html.erb
<div class="phones-list">
    <div class="container">
        <% @phones.each do |phone| %>
            
            <% @charValues = phone.characteristic_values.all %>
            <div class="phone-wrapper">
            
                <div class="container-fluid">
                    <div class="row">

                        <div class="col-xs-12 col-sm-3">
                          
                            <% if !phone.image_id.nil? %>
                                <%= link_to phone_path(phone), { :class => "image-wrapper"} do %>
                                     <%= image_tag url_for(:controller => "images", :action => "show", :id => phone.image_id) %>
                                <% end %>
                            <% end %>
                        </div>
                        
                        <div class="col-xs-12 col-sm-9">
                              
                            <%= link_to phone.name, phone_path(phone), { :class => "name"} %>
                          
                            <div class="realese-date"><%= phone.realese_date %></div>
                          
                            <div class="rating">
                                
                                <% @k = 5 - phone.rating %>
                                <% for @i in 1..phone.rating %>
                                    <i aria-hidden="true" class="fa fa-star"></i>
                                <% end %>
                            
                                <% for @i in 1..@k %>
                                    <i aria-hidden="true" class="fa fa-star-o"></i>
                                <% end %>
                                
                            </div>
                            
                            <div class="description">
                                <%= phone.description %>
                            </div>
                            
                            <div class="price">
                                <%= number_to_currency(phone.price, precision: 0, delimiter: " ", unit: "") %> <i aria-hidden="true" class="fa fa-rouble"></i>
                            </div>
                            
                            <div class="order-form-btn" data-phone-id="<%= phone.id %>">Купить</div>
                            
                            <% if !@charValues.blank? %>
                                <div class="show-characteristics" onclick="">показать характеристики</div>
                            <% end %>
                      
                        </div>
                    </div>
                    
                    <% if !@charValues.blank? %>
                        <div class="characteristics-wrapper container-fluid">
                            <% @charValues.each do |charValue| %>
            
                                <div class='characteristic-wrapper row'>
                                    <div class='char-name col-xs-6'>
                                        <%= charValue.characteristic_type.name %>
                                    </div>
                                    <div class='char-value col-xs-6'>
                                        <%= charValue.value %>
                                    </div>
                                </div>
                                
                            <% end %>
                        </div>
                    <% end %>
                </div>
                
            </div>
      
        <% end %>
    </div>
</div>

<div class="container">
    <div class="bottom-page-links">
        <%= link_to "Добавить телефон", new_phone_path, { :class => "btn btn-primary btn-block"} %>
    </div>
</div>


<div class="modal fade" tabindex="-1" role="dialog" id="order-form">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"<i class="fa fa-times" aria-hidden="true"></i></span></button>
        <h4 class="modal-title">Оформить заказ</h4>
      </div>
      <div class="modal-body">
        <div class="form-wrapper">
            <%= form_with model: @order, local: true do |form| %>
            
              <% if @order.errors.any? %>
                <div class="form-errors">
                    Производитель не был добавлен. Были обнаружены следующие ошибки:
                  <ul>
                    <% @order.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            
              <div class="form-group">
                <%= form.label :name, {:value => "Имя"} %>
                <%= form.text_field :name , { :class => "form-control", :required => true} %>
              </div>
             
             <div class="form-group">
               <%= form.label :phone_number, { :value => "Телефон"} %>
               <%= form.text_field :phone_number, { :class => "form-control", :mask => "phone"} %>
             </div>
        
             <%= form.hidden_field :phone_id, { :id => "phone-id"} %>
             
              <%= form.submit "Отправить", { :class => "btn btn-primary" } %>
              
            <% end %>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/phones/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

<div class="container">
  <div class="bottom-page-links">
    <%= link_to "Телефоны", phones_path, { :class => "btn btn-primary btn-block" } %>
  </div>
</div>

app/views/phones/show.html.erb
<div class="phone-wrapper">
    <div class="container">
        <div class="row">
    
            <div class="col-xs-12 col-sm-3">
              
                <% if !@phone.image_id.nil? %>
                    <div class="image-wrapper">
                        <%= image_tag url_for(:controller => "images", :action => "show", :id => @phone.image_id) %>
                    </div>
                <% end %>
            </div>
            
            <div class="col-xs-12 col-sm-9">
                
                <div class="realese-date"><%= @phone.realese_date %></div>
              
                <div class="rating">
                    
                    <% @k = 5 - @phone.rating %>
                    <% for @i in 1..@phone.rating %>
                        <i aria-hidden="true" class="fa fa-star"></i>
                    <% end %>
                
                    <% for @i in 1..@k %>
                        <i aria-hidden="true" class="fa fa-star-o"></i>
                    <% end %>
                    
                </div>
                
                <div class="description">
                    <%= @phone.description %>
                </div>
                
                <div class="price">
                    <%= number_to_currency(@phone.price, precision: 0, delimiter: " ", unit: "") %> <i aria-hidden="true" class="fa fa-rouble"></i>
                </div>
                
                <div class="order-form-btn" data-phone-id="<%= @phone.id %>">Купить</div>
                
                <% @charValues = @phone.characteristic_values
                 if !@charValues.blank? %>
                    <div class="show-characteristics" onclick="">показать характеристики</div>
                <% end %>  
            </div>
        </div>
        
        <% if !@charValues.blank? %>
        
            <div class="characteristics-wrapper container-fluid">
                <% @charValues.each do |charValue| %>
            
                <div class='characteristic-wrapper row'>
                    <div class='char-name col-xs-6'>
                        <%= charValue.characteristic_type.name %>
                    </div>
                    <div class='char-value col-xs-6'>
                        <%= charValue.value %>
                    </div>
                    <div class="absolute-buttons">
                        <span class="btn btn-default show-edit-form">Изменить</span>
                        <%= link_to "Удалить", phone_characteristic_value_path(charValue.phone, charValue),
                            method: :delete, 
                            :class => "btn btn-warning",
                            data: {
                                confirm: "Вы уверены?",
                            } 
                        %>
                    </div>
                    <div class="form-wrapper">
                    
                        <%= form_with scope: charValue, url: phone_characteristic_value_path(charValue.phone_id, charValue), :method => :put, local: true do |form| %>
                
                            <h3>Добавить характеристику</h3>
                
                            <div class="form-group">
                                <%= form.label :value, "Значение" %>
                                <%= form.text_field :value , { :class => "form-control", :required => true} %>
                            </div>
                            
                            <div class="form-group">
                                <%= form.label :characteristic_type_id, "Модель" %>
                                <%= form.collection_select(:characteristic_type_id, CharacteristicType.all, :id, :name, {}, { :class => "form-control"}) %>
                            </div>
                            
                            <%= form.submit "Отправить", { :class => "btn btn-primary" } %>
                        <% end %>
                    </div>
                </div>
                <% end %>
            </div>
        <% end %>
        
        <div class="form-wrapper">
            <%= form_with(model: [@phone, @phone.characteristic_values.build], local: true) do |form| %>
                
                <h3>Добавить характеристику</h3>
                
                <div class="form-group">
                    <%= form.label :value, "Значение" %>
                    <%= form.text_field :value , { :class => "form-control", :required => true} %>
                </div>
                
                <div class="form-group">
                    <%= form.label :characteristic_type_id, "Модель" %>
                    <%= form.collection_select(:characteristic_type_id, CharacteristicType.all, :id, :name, {}, { :class => "form-control"}) %>
                </div>
                
                <%= form.submit "Отправить", { :class => "btn btn-primary" } %>
            <% end %>
        </div>
        
    </div>
</div>

<div class="container">
    <div class="bottom-page-links">
        
        <%= link_to "Изменить", edit_phone_path(@phone), {
                :class => "btn btn-default btn-block"
            }
        %>
        <%= link_to "Удалить", phone_path(@phone),
                    method: :delete, 
                    :class => "btn btn-warning btn-block",
                    data: {
                        confirm: "Вы уверены?",
                    } 
        %>
        
        <%= link_to "Телефоны", phones_path, { :class => "btn btn-primary btn-block" } %>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="order-form">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"<i class="fa fa-times" aria-hidden="true"></i></span></button>
        <h4 class="modal-title">Оформить заказ</h4>
      </div>
      <div class="modal-body">
        <div class="form-wrapper">
            <%= form_with model: @order, local: true do |form| %>
            
              <% if @order.errors.any? %>
                <div class="form-errors">
                    Производитель не был добавлен. Были обнаружены следующие ошибки:
                  <ul>
                    <% @order.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            
              <div class="form-group">
                <%= form.label :name, {:value => "Имя"} %>
                <%= form.text_field :name , { :class => "form-control", :required => true} %>
              </div>
             
             <div class="form-group">
               <%= form.label :phone_number, { :value => "Телефон"} %>
               <%= form.text_field :phone_number, { :class => "form-control", :mask => "phone"} %>
             </div>
        
             <%= form.hidden_field :phone_id, { :id => "phone-id"} %>
             
              <%= form.submit "Отправить", { :class => "btn btn-primary" } %>
              
            <% end %>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->