config/routes.rb
Rails.application.routes.draw do
    
  get 'images/show'

    resources :brands do
       resources :models 
    end
    
    resources :characteristic_types
    
    resources :phones do
        resources :characteristic_values
    end
    
    resources :images
    
    resources :orders
    
    root 'phones#index'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/characteristic_types_controller.rb
class CharacteristicTypesController < ApplicationController
    
    before_action :authenticate, :except => [:index]
    
    def index
       
       @pageTitle = "Типы характеристик"
       @charTypes = CharacteristicType.all
    end
    
    def show
        @charType = CharacteristicType.find(params[:id])
        @pageTitle = @charType.name
    end
    
    def new
        
        @pageTitle = "Добавить тип характеристики"
        @charType = CharacteristicType.new
        
    end
    
    def edit 
        
        @charType = CharacteristicType.find(params[:id])
        @pageTitle = @charType.name
    end
    
    def create
        
        @charType = CharacteristicType.new(characteristic_type_params)
        
        if @charType.save
            @pageTitle = @charType.name
            redirect_to characteristic_types_path
        else
            @pageTitle = "Добавить тип"
            render new_characteristic_type_path
        end
    end
    
    def update
       
       @charType = CharacteristicType.find(params[:id])
       if @charType.update(characteristic_type_params)
           @pageTitle = @charType.name
            redirect_to @charType
       else 
            render edit_characteristic_type_path(@brand)
       end
    end
    
    def destroy
        
      @charType = CharacteristicType.find(params[:id])
      @charType.destroy
     
      redirect_to characteristic_types_path
    end
    
    
    private
    
        def characteristic_type_params
           params.require(:characteristic_type).permit(:name)
        end
end

app/views/characteristic_types/_form.html.erb
  <div class="form-wrapper">
    <%= form_with model: @charType, local: true do |form| %>
    
      <% if @charType.errors.any? %>
        <div class="form-errors">
            Производитель не был добавлен. Были обнаружены следующие ошибки:
          <ul>
            <% @charType.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= form.label :name, "Имя" %>
        <%= form.text_field :name , { :class => "form-control", :required => true} %>
      </div>
     
      <%= form.submit "Отправить", { :class => "btn btn-primary" } %>
      
    <% end %>
  </div>

app/views/characteristic_types/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

<div class="container">
  <div class="bottom-page-links">
    <%= link_to "Типы характеристик", characteristic_types_path, { :class => "btn btn-primary btn-block" } %>
  </div>
</div>

app/views/characteristic_types/index.html.erb
<div class="container">
<ol class="list-group">
    <% @charTypes.each do |charType| %>
        <li class="list-group-item clearfix">
            <span class="title">
                <%= charType.name %>
            </span>
            <span class="list-item-buttons">
                <%= link_to "Подробнее", characteristic_type_path(charType), {
                :class => "btn btn-small btn-info"
                } %>
                <%= link_to "Изменить", edit_characteristic_type_path(charType), {
                :class => "btn btn-small btn-default"
                } %>
                <%= link_to "Удалить", characteristic_type_path(charType),
                    method: :delete, 
                    :class => "btn btn-warning",
                    data: {
                        confirm: "Вы уверены?",
                    } 
                %>
            </span>
        </li>
    <% end %>
</ol>

<%= link_to "Добавить тип характеристик", new_characteristic_type_path, { :class => "btn btn-primary btn-block"} %>

</div>

app/views/characteristic_types/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

<div class="container">
  <div class="bottom-page-links">
    <%= link_to "Типы характеристик", characteristic_types_path, { :class => "btn btn-primary btn-block" } %>
  </div>
</div>

app/views/characteristic_types/show.html.erb
<div class="container">
    <div class="bottom-page-links">
        
        <%= link_to "Изменить", edit_characteristic_type_path(@charType), {
                :class => "btn btn-default btn-block"
            }
        %>
        <%= link_to "Удалить", characteristic_type_path(@charType),
                    method: :delete, 
                    :class => "btn btn-warning btn-block",
                    data: {
                        confirm: "Вы уверены?",
                    } 
        %>
        
        <%= link_to "Типы характеристик", characteristic_types_path, { :class => "btn btn-primary btn-block" } %>
    </div>
</div>