config/routes.rb
Rails.application.routes.draw do
    
  get 'images/show'

    resources :brands do
       resources :models 
    end
    
    resources :characteristic_types
    
    resources :phones do
        resources :characteristic_values
    end
    
    resources :images
    
    resources :orders
    
    root 'phones#index'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :models, dependent: :destroy
    validates :name, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    
   before_action :authenticate, :except => [:index, :show]
    
    def index
       
       @pageTitle = "Бренды"
       @brands = Brand.all
    end
    
    def show
        
        @brand = Brand.find(params[:id])
        @pageTitle = @brand.name
    end
    
    def new
       
       @pageTitle = "Добавить бренд"
       @brand = Brand.new
    end
    
    def edit
        
        @brand = Brand.find(params[:id])
        @pageTitle = @brand.name
    end
    
    def create
        
        @brand = Brand.new(brand_params)
        
        if @brand.save
            @pageTitle = @brand.name
            redirect_to @brand
        else
            @pageTitle = "Добавить бренд"
            render new_brand_path
        end
    end
    
    def update
       
       @brand = Brand.find(params[:id])
       if @brand.update(brand_params)
           @pageTitle = @brand.name
            redirect_to @brand
       else 
            render edit_brand_path(@brand)
       end
    end
    
    def destroy
        
      @brand = Brand.find(params[:id])
      @brand.destroy
     
      redirect_to brands_path
    end
    
    private
    
        def brand_params
           params.require(:brand).permit(:name, :description)
        end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
  <div class="form-wrapper">
    <%= form_with model: @brand, local: true do |form| %>
    
      <% if @brand.errors.any? %>
        <div class="form-errors">
            Производитель не был добавлен. Были обнаружены следующие ошибки:
          <ul>
            <% @brand.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= form.label :name, {:value => "Имя"} %>
        <%= form.text_field :name , { :class => "form-control", :required => true} %>
      </div>
     
     <div class="form-group">
       <%= form.label :description, { :value => "Описание"} %>
       <%= form.text_area :description, { :class => "form-control"} %>
     </div>
     
      <%= form.submit "Отправить", { :class => "btn btn-primary" } %>
      
    <% end %>
  </div>

app/views/brands/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

<div class="container">
  <div class="bottom-page-links">
    <%= link_to "Бренды", brands_path, { :class => "btn btn-primary btn-block" } %>
  </div>
</div>

app/views/brands/index.html.erb
<div class="container">
<ol class="list-group">
    <% @brands.each do |brand| %>
        <li class="list-group-item clearfix">
            <span class="title">
                <%= brand.name %>
            </span>
            <span class="list-item-buttons">
                <%= link_to "Подробнее", brand_path(brand), {
                :class => "btn btn-small btn-info"
                } %>
                <%= link_to "Изменить", edit_brand_path(brand), {
                :class => "btn btn-small btn-default"
                } %>
                <%= link_to "Удалить", brand_path(brand),
                    method: :delete, 
                    :class => "btn btn-warning",
                    data: {
                        confirm: "Вы уверены?",
                    } 
                %>
            </span>
        </li>
    <% end %>
</ol>

<%= link_to "Добавить бренд", new_brand_path, { :class => "btn btn-primary btn-block"} %>

</div>

app/views/brands/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

<div class="container">
  <div class="bottom-page-links">
    <%= link_to "Бренды", brands_path, { :class => "btn btn-primary btn-block" } %>
  </div>
</div>

app/views/brands/show.html.erb
<div class="container">
    
    <div class="description-wrapper">
        <%= @brand.description %>
    </div>
</div>

<div class="container">
    <div class="bottom-page-links">
        
        <%= link_to "Изменить", edit_brand_path(@brand), {
                :class => "btn btn-default btn-block"
            }
        %>
        <%= link_to "Удалить", brand_path(@brand),
                    method: :delete, 
                    :class => "btn btn-warning btn-block",
                    data: {
                        confirm: "Вы уверены?",
                    } 
        %>
        
        <%= link_to "Бренды", brands_path, { :class => "btn btn-primary btn-block" } %>
    </div>
</div>

<div class="container">
    <h2>Модели</h2>
    
    <ol class="list-group">
        <% @brand.models.each do |model| %>
        
            <li class="list-group-item">
                
                <span class="title"><%= model.name %></span>
                <span class="list-item-buttons">
                    
                    <span class="btn btn-default show-edit-form">Изменить</span>
                    <%= link_to "Удалить", brand_model_path(model.brand, model),
                        method: :delete, 
                        :class => "btn btn-warning",
                        data: {
                            confirm: "Вы уверены?",
                        } 
                    %>
                </span>
                
                <div class="form-wrapper">
                    
                    <%= form_with scope: model, url: brand_model_path(model.brand_id, model), :method => :put, local: true do |form| %>
            
                        <h3>Изменить модель</h3>
                        
                        <div class="form-group">
                            <%= form.label :name, "Имя" %>
                            <%= form.text_field :name , { :class => "form-control", :required => true} %>
                        </div>
                          
                          
                        <%= form.submit "Отправить", { :class => "btn btn-primary" } %>
                    <% end %>
                </div>
            </li>
        <% end %>
    </ol>
    
    <div class="form-wrapper">
        <%= form_with(model: [@brand, @brand.models.build], local: true) do |form| %>
            
            <h3>Добавить модель</h3>
            
            <div class="form-group">
                <%= form.label :name, "Имя" %>
                <%= form.text_field :name , { :class => "form-control", :required => true} %>
            </div>
              
            <%= form.submit "Отправить", { :class => "btn btn-primary" } %>
        <% end %>
    </div>
</div>