config/routes.rb
Rails.application.routes.draw do
    
  get 'images/show'

    resources :brands do
       resources :models 
    end
    
    resources :characteristic_types
    
    resources :phones do
        resources :characteristic_values
    end
    
    resources :images
    
    resources :orders
    
    root 'phones#index'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @pageTitle %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        rel="stylesheet" 
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
        crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" 
        rel="stylesheet" 
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" 
        crossorigin="anonymous">
    <script
      src="https://code.jquery.com/jquery-1.12.4.min.js"
      integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous"></script>
      
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'phones', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'orders', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
    
    <header>
      <div class="container">
        <div class="row">
          <div class="hidden-xs col-sm-3">
           <a href="/" class="logo" >PhoneList</a>
          </div>
          <div class="hidden-sm col-xs-2 hidden-md hidden-lg">
            <a class="logo" href="/"><i class='fa fa-mobile' aria-hidden='true'></i></a>
          </div>
          <div class="col-xs-10 col-sm-9">
            <nav class="main-menu">
              
              <div class="menu-item">
                <%= link_to "Телефоны", phones_path %>
                <div class="sub_menu-items">
                  <%= link_to "Добавить телефон", new_phone_path %>
                </div>
              </div>
              
              <div class="menu-item">
                <%= link_to "Бренды", brands_path %>
                <div class="sub_menu-items">
                  <%= link_to "Добавить бренд", new_brand_path %>
                </div>
              </div>
              
              <div class="menu-item">
                <%= link_to "Типы характеристик", characteristic_types_path %>
                <div class="sub_menu-items">
                  <%= link_to "Добавить тип", new_characteristic_type_path %>
                </div>
              </div>
              
              <div class="menu-item">
                <%= link_to "Заказы", orders_path %>
              </div>
              
            </nav>
          </div>
        </div>
      </div>
    </header>

    <div class="header-block">
      <div class="container">
        <h1><%= @pageTitle %></h1>
      </div>
    </div>
    
    <%= yield %>
    
    <footer>
      <div class="copyright">
        <i aria-hidden="true" class="fa copyright"></i> 2017 - PhonesList, Граб Н. Ю.
      </div>
    </footer>
  
  </body>
</html>